#!/bin/bash
set -euo pipefail

log() { echo ""; echo "==> $*"; }

die() { echo "ОШИБКА: $*" >&2; exit 1; }

# Проверяем, что скрипт выполняется от root
if [ "$(id -u)" -ne 0 ]; then
  die "Этот скрипт должен быть запущен с правами root."
fi

# Запрос имени сервера
read -p "Введите имя сервера (например, m1): " SERVER_NAME

if [ -z "$SERVER_NAME" ]; then
  die "Имя сервера не может быть пустым."
fi

# Запрос CF_Token
read -p "Введите Cloudflare API Token (CF_Token): " CF_TOKEN
if [ -z "$CF_TOKEN" ]; then
  die "CF_Token не может быть пустым."
fi

# Порт API
API_PORT=8000
API_DIR=/root/api

log "Обновление системы и установка зависимостей..."
apt update -y
apt install -y software-properties-common wget git apt-transport-https ca-certificates curl gnupg2 libnss3-tools vnstat openssl cron

log "Добавление ключей авторизации..."
cat <<EOL > ~/.ssh/authorized_keys
# Felix
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9RhJj7Gh+RX9CUYlTkpDzr8X4tt1GMTNN+6pr+BZbo1aXDBMDajNaDbSlWII/1DU2haz8JssO/30McO2RxYvb+L4jtGN/sW69rZpGyffPOjkZyI/Z4f/Cb2dLGnqEkkqTHn3hgoR6YNFagnVJFGbLY7dfz9IfIFv5JbZgpjXEBNciZKq/45IkxGSSxi76+YLbQvlVXpU5vo0iHqHArTd1PDTuZ15LdJqCpjTSQ95/KgJB3vubGTgYb1/U5fQcZhBl3kmgPIX57m/GEZHCQp5rNAx0CbcIBW+e76A4syjRkucn4aeNdcrOsVOIBmlO6MLJtx2IJfbwHqr8ogPxV3UNYTU5oFKBT7e+oh2fTVCSe0S/qQr5T2kgbcR+C1yAcVHmCIZfb421WGcMCDhP1971/G3JOwJH2ncy0Pj7E4ZCsce3mVEV+Rvryc2SQ9otsgpDvhJzkJ1OrgnzVmTVOCt1imiq425x75vHOPg76x9pL7AjABsoKt3o0nuWZ5nc2g0t19NANp8ADFGxN1XS/VEdD45p17xuyrtkWqxdR0dss0PHpwK6SkmfxAh+pEfAfwcU/DgkaGx1+A45REhag1blt45M7zafoqKq9j9rrc5XPKbAHGv9IhA779NrccYOxIfTQpGe3TMaxZYr1Wy/eFoPwksoIHeqIZIHvyoQoPb8Dw== Generated By Termius

# Fajox
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEguoC4RwhFAM/C5arbtrVCW9Zb804ZDTEqdxhu8gzR2Mf2oXt0UvOG/EJy7WkNOiKHVr/xv7ye8RnQ6/YVh4CZy9CMP4MFkUAzk4UpaSZWmIig9L/yl1y3VELX6mPDjNCEgo4WoviOpwye4kYE9rzB0xNpRo7WKB+2oyE+2gwDnebFGgByxUyI5bKrb6styvVhLBvu/EMDHJgmXLhKc8Q+CaEE/Z/8UOoZCUaFfbjLiJddnKNCKpQMkJ5fzHSftOgWFT6D9XvNrV0p2xUeUpUi7TUYWD9SqZNh8T/LpJ2Twoht3bwUzjGdq4+wQ0spPa2+Atl1l4Vh1GG/8OV8AzAtD+Da+N6Z+bGQeR+Pb34s65jsF/Pm3AroidG43U6Lk2ALf+BAybzQmXkZdwQC9/qAuHgccUTOh6ym3AqikI/LLPbpnEHwX0jEWfnFIJ1OkR6yEDK22ZcTUHKvmd78WNLj10d+EzQW5YmnI4TuN6OETSHMykP4C7ckcrJjkbfxw5DiM+VFNo0g0g528Cd6sFJ99Gc783Wuv7uuzVBkT1Qfwv99e/JEDs/RUObWFfU7hiDYOXXvrms3ppbA3z9r1O4usJfjG0lsMNXg67ZWQlmcMUf0vX972mnCGSb2WSdDthstvbJo3l6RauexTxIHwqwV8zdyjaMcB9LUUNTX/XuDw== fajox@hikka.host

# Vsecoder
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVm0RrnFGsM7FWBMKi/C1voECAv0A6jl6C8ekgPsE4WYF36jS0xyJNKdsOkKPLLA9k+AvkyGTQ0kRUjSjGk6VdNt/LhyGnu4/0pHdWk2mGdXj+Gllj9crboIB+5NZer7M/Lywv9NJ+jJTmx29Z/kmPdBfnHB4gvI4qMnkGkiJ3ZtHiUsVa514hAnglaBYVHHoYK/8AdPLZQm3xr4e00UBlN20L6T7LbxaCIn93an+RaGRrpANtoo2jVkrpw8PTzz39MiP1ttyCRn+wnouyF425bO3rhPsW4RRwM+h9i6lX8tYMUEl5iXn5XE4yY3LXQsUIh3o7aO4Q6o3lxH8NvvoToxd89Rk4CJgkN9j7V0GpQabryQmXSACkFPetAOcppv/cDztO3gOTs4FHOaYwUf73OyrVyqZv7vvWyOv4ocvn+4E1eu4IdQBePO5HqJABNOzv2QYTOQIKaJSHjsgXuA76fhqIY95aGNn3+LclNO2EH/OXp4Rrm+xh5eUZNIpGeOz5DpCEVs7nl07pfONcIkdDZwYBvOicbQWplH5SBPxONSgkejhWLxYoo4ZqiXyMf2OvRsQBM+Y4n5WQjI49LzWYYVhBVzd1bfxWi1Nbf+6NF4kkd8mswpv8E3A8BL2EPu2WSAQAS2otK+BtoTQUy+bEmW5OUvgnTSzTa1kJWiTjuw== Generated By Termius
EOL

log "Установка Python 3.8 и Docker..."
add-apt-repository ppa:deadsnakes/ppa -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
apt update -y
apt install -y python3.8 python3.8-distutils python3.8-venv docker-ce

log "Установка Node.js LTS (нужен для сборки UI при старте python -m app)..."
curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
apt install -y nodejs
node -v
npm -v

log "Установка pip для Python 3.8..."
wget -q https://bootstrap.pypa.io/pip/3.8/get-pip.py -O /tmp/get-pip.py
python3.8 /tmp/get-pip.py
python3.8 -m pip install -U wheel virtualenv

log "Клонирование / обновление репозитория API..."
if [ -d "$API_DIR/.git" ]; then
  git -C "$API_DIR" pull --ff-only
else
  git clone -b main https://github.com/hikkahost/api "$API_DIR"
fi
cd "$API_DIR"

log "Виртуальное окружение и Python-зависимости..."
python3.8 -m venv venv
# shellcheck disable=SC1091
source venv/bin/activate
python3.8 -m pip install -U pip
python3.8 -m pip install -r requirements.txt

[ -d web ] || die "Нет каталога api/web — UI соберётся при первом запуске python -m app"

log "Тестовая конфигурация (для pytest)..."
cat <<EOL > app/config.py
CONTAINER = {
    "cpu": 1.0,
    "memory": "512M",
    "size": "5g",
    "rate": "50mbit",
    "burst": "32kbit",
    "latency": "400ms",
}

SERVER = "$SERVER_NAME"

class Config:
    SECRET_KEY = "secret"
EOL

log "Запуск unit-тестов (setup_web, без Docker)..."
SETUP_WEB_SKIP_BUILD=1 python3.8 -m pytest app/tests/test_setup_web.py -v --tb=short

log "Запуск API-тестов (mock Docker)..."
SETUP_WEB_SKIP_BUILD=1 python3.8 -m pytest app/tests/test_docker.py -v --tb=short

log "Генерация секретного ключа..."
SECRET_KEY=$(openssl rand -base64 32)
echo "Секретный ключ: $SECRET_KEY"

log "Финальная конфигурация..."
cat <<EOL > app/config.py
CONTAINER = {
    "cpu": 1.0,
    "memory": "512M",
    "size": "5g",
    "rate": "50mbit",
    "burst": "32kbit",
    "latency": "400ms",
}

SERVER = "$SERVER_NAME"

class Config:
    SECRET_KEY = "$SECRET_KEY"
EOL

log "SSL-сертификаты (acme.sh + Let's Encrypt + Cloudflare DNS)..."
mkdir -p /etc/ssl
export CF_Token="$CF_TOKEN"
export INSTALL_SKIP_CRON=1
curl -fsSL https://get.acme.sh | sh
~/.acme.sh/acme.sh --set-default-ca --server letsencrypt
~/.acme.sh/acme.sh --register-account -m dev.fajox@gmail.com --server letsencrypt || true

ACME_DOMAIN="${SERVER_NAME}.hikka.host"
~/.acme.sh/acme.sh --issue --dns dns_cf \
  -d "$ACME_DOMAIN" \
  -d "*.$ACME_DOMAIN" \
  --server letsencrypt \
  --force

~/.acme.sh/acme.sh --install-cert -d "$ACME_DOMAIN" \
  --key-file /etc/ssl/cloudflare-origin.key \
  --fullchain-file /etc/ssl/cloudflare-origin.crt \
  --reloadcmd "systemctl reload caddy || true"

[ -f /etc/ssl/cloudflare-origin.crt ] && [ -f /etc/ssl/cloudflare-origin.key ] \
  || die "Сертификаты не установлены в /etc/ssl/"

chown caddy:caddy /etc/ssl/cloudflare-origin.crt /etc/ssl/cloudflare-origin.key 2>/dev/null \
  || chown root:root /etc/ssl/cloudflare-origin.crt /etc/ssl/cloudflare-origin.key
chmod 640 /etc/ssl/cloudflare-origin.*

log "Установка Caddy..."
apt install -y debian-keyring debian-archive-keyring
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' > /etc/apt/sources.list.d/caddy-stable.list
apt update -y
apt install -y caddy

log "Конфигурация Caddy..."
mkdir -p /etc/caddy/conf.d /var/log/caddy
CADDY_BAK="/etc/caddy/conf.d.bak.$(date +%s)"
if compgen -G "/etc/caddy/conf.d/*.caddy" > /dev/null; then
  mkdir -p "$CADDY_BAK"
  mv /etc/caddy/conf.d/*.caddy "$CADDY_BAK/" || true
  log "Старые vhost перенесены в $CADDY_BAK"
fi

cat <<EOL > /etc/caddy/conf.d/api."$SERVER_NAME".hikka.host.caddy
api.$SERVER_NAME.hikka.host {
    tls /etc/ssl/cloudflare-origin.crt /etc/ssl/cloudflare-origin.key
    reverse_proxy 127.0.0.1:$API_PORT
}
EOL

cat <<EOL > /etc/caddy/Caddyfile
import /etc/caddy/conf.d/*.caddy
EOL

chown -R root:caddy /etc/caddy
chmod -R 755 /etc/caddy
chown caddy:caddy /etc/ssl/cloudflare-origin.crt /etc/ssl/cloudflare-origin.key 2>/dev/null || true
chmod 640 /etc/ssl/cloudflare-origin.*

if ! caddy validate --config /etc/caddy/Caddyfile 2>&1; then
  echo "--- journalctl -u caddy (last 30 lines) ---"
  journalctl -u caddy -n 30 --no-pager || true
  die "Caddy: невалидный Caddyfile (см. выше). Старые конфиги: $CADDY_BAK"
fi

systemctl enable caddy
systemctl restart caddy || {
  echo "--- journalctl -u caddy (last 30 lines) ---"
  journalctl -u caddy -n 30 --no-pager || true
  die "Caddy: не удалось запустить сервис."
}
systemctl is-active --quiet caddy || die "Caddy не запустился: journalctl -u caddy -n 40"

log "Systemd-сервис API (:8000 + setup_web :8001, UI build при старте)..."
cat <<EOL > /etc/systemd/system/api.service
[Unit]
Description=HikkaHost API and setup_web
After=network.target docker.service

[Service]
WorkingDirectory=$API_DIR
Environment=SANIC_TOUCHUP=0
Environment=API_BIND_HOST=0.0.0.0
Environment=API_PORT=8000
Environment=SETUP_BIND_HOST=127.0.0.1
ExecStart=$API_DIR/venv/bin/python3.8 -m app
Type=simple
Restart=always
RestartSec=3
User=root

[Install]
WantedBy=multi-user.target
EOL

systemctl daemon-reload
systemctl enable api.service
systemctl restart api.service

log "Cron-задачи..."
systemctl enable --now cron

cat <<'SCRIPT' > /root/hikkahost-pull-images.sh
#!/bin/bash
set -euo pipefail
for tag in hikka heroku legacy geektg; do
  docker pull "fajox/hikkahost:${tag}" >/dev/null 2>&1 || true
done
docker image prune -a -f >/dev/null 2>&1 || true
SCRIPT
chmod +x /root/hikkahost-pull-images.sh

# Один cron для acme (acme.sh install не добавляет свой — INSTALL_SKIP_CRON=1)
(crontab -l 2>/dev/null | grep -v acme.sh || true; echo '27 12 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null') | crontab -
(crontab -l 2>/dev/null | grep -v hikkahost-pull-images || true; echo '0 0 * * * /root/hikkahost-pull-images.sh') | crontab -
(crontab -l 2>/dev/null | grep -v '/sbin/reboot' || true; echo '0 0 * * 1 /sbin/reboot') | crontab -

if [ -f reinitcaddy.py ]; then
  log "Обновление user vhost (Caddy → setup_web :8001)..."
  "$API_DIR/venv/bin/python3.8" reinitcaddy.py || true
  systemctl reload caddy || systemctl restart caddy
fi

log "Проверка сервисов (первый старт api может занять время — сборка web)..."
sleep 5
for i in 1 2 3 4 5 6 7 8 9 10; do
  if curl -sf "http://127.0.0.1:${API_PORT}/" >/dev/null 2>&1; then
    break
  fi
  if [ "$i" -eq 10 ]; then
    die "API :${API_PORT} не отвечает (journalctl -u api -n 50)"
  fi
  sleep 6
done
systemctl is-active --quiet caddy || die "Caddy не запущен (journalctl -u caddy)"
systemctl is-active --quiet api || die "API не запущен (journalctl -u api)"

IP_ADDRESS=$(hostname -I | awk '{print $1}')
echo ""
echo "Готово."
echo "  API:    https://api.$SERVER_NAME.hikka.host  →  $IP_ADDRESS:$API_PORT"
echo "  Setup:  https://{userId}.$SERVER_NAME.hikka.host  →  setup_web :8001"
echo "  SECRET: $SECRET_KEY"
echo "  Проверка: systemctl status api caddy && journalctl -u api -n 30"
