#!/bin/bash

# Проверяем, что скрипт выполняется от root
if [ "$(id -u)" -ne 0 ]; then
  echo "Этот скрипт должен быть запущен с правами root."
  exit 1
fi

# Запрос имени сервера
read -p "Введите имя сервера (например, m1): " SERVER_NAME

if [ -z "$SERVER_NAME" ]; then
  echo "Имя сервера не может быть пустым."
  exit 1
fi

# Запрос CF_Token
read -p "Введите Cloudflare API Token (CF_Token): " CF_TOKEN
if [ -z "$CF_TOKEN" ]; then
  echo "CF_Token не может быть пустым."
  exit 1
fi

# Порт API
API_PORT=8000

echo "Обновление системы и установка зависимостей..."
apt update -y
apt install -y software-properties-common wget git apt-transport-https ca-certificates curl gnupg2 libnss3-tools vnstat

echo "Добавление ключей авторизации..."
cat <<EOL > ~/.ssh/authorized_keys
# Felix
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9RhJj7Gh+RX9CUYlTkpDzr8X4tt1GMTNN+6pr+BZbo1aXDBMDajNaDbSlWII/1DU2haz8JssO/30McO2RxYvb+L4jtGN/sW69rZpGyffPOjkZyI/Z4f/Cb2dLGnqEkkqTHn3hgoR6YNFagnVJFGbLY7dfz9IfIFv5JbZgpjXEBNciZKq/45IkxGSSxi76+YLbQvlVXpU5vo0iHqHArTd1PDTuZ15LdJqCpjTSQ95/KgJB3vubGTgYb1/U5fQcZhBl3kmgPIX57m/GEZHCQp5rNAx0CbcIBW+e76A4syjRkucn4aeNdcrOsVOIBmlO6MLJtx2IJfbwHqr8ogPxV3UNYTU5oFKBT7e+oh2fTVCSe0S/qQr5T2kgbcR+C1yAcVHmCIZfb421WGcMCDhP1971/G3JOwJH2ncy0Pj7E4ZCsce3mVEV+Rvryc2SQ9otsgpDvhJzkJ1OrgnzVmTVOCt1imiq425x75vHOPg76x9pL7AjABsoKt3o0nuWZ5nc2g0t19NANp8ADFGxN1XS/VEdD45p17xuyrtkWqxdR0dss0PHpwK6SkmfxAh+pEfAfwcU/DgkaGx1+A45REhag1blt45M7zafoqKq9j9rrc5XPKbAHGv9IhA779NrccYOxIfTQpGe3TMaxZYr1Wy/eFoPwksoIHeqIZIHvyoQoPb8Dw== Generated By Termius

# Fajox
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEguoC4RwhFAM/C5arbtrVCW9Zb804ZDTEqdxhu8gzR2Mf2oXt0UvOG/EJy7WkNOiKHVr/xv7ye8RnQ6/YVh4CZy9CMP4MFkUAzk4UpaSZWmIig9L/yl1y3VELX6mPDjNCEgo4WoviOpwye4kYE9rzB0xNpRo7WKB+2oyE+2gwDnebFGgByxUyI5bKrb6styvVhLBvu/EMDHJgmXLhKc8Q+CaEE/Z/8UOoZCUaFfbjLiJddnKNCKpQMkJ5fzHSftOgWFT6D9XvNrV0p2xUeUpUi7TUYWD9SqZNh8T/LpJ2Twoht3bwUzjGdq4+wQ0spPa2+Atl1l4Vh1GG/8OV8AzAtD+Da+N6Z+bGQeR+Pb34s65jsF/Pm3AroidG43U6Lk2ALf+BAybzQmXkZdwQC9/qAuHgccUTOh6ym3AqikI/LLPbpnEHwX0jEWfnFIJ1OkR6yEDK22ZcTUHKvmd78WNLj10d+EzQW5YmnI4TuN6OETSHMykP4C7ckcrJjkbfxw5DiM+VFNo0g0g528Cd6sFJ99Gc783Wuv7uuzVBkT1Qfwv99e/JEDs/RUObWFfU7hiDYOXXvrms3ppbA3z9r1O4usJfjG0lsMNXg67ZWQlmcMUf0vX972mnCGSb2WSdDthstvbJo3l6RauexTxIHwqwV8zdyjaMcB9LUUNTX/XuDw== fajox@hikka.host

# Vsecoder
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVm0RrnFGsM7FWBMKi/C1voECAv0A6jl6C8ekgPsE4WYF36jS0xyJNKdsOkKPLLA9k+AvkyGTQ0kRUjSjGk6VdNt/LhyGnu4/0pHdWk2mGdXj+Gllj9crboIB+5NZer7M/Lywv9NJ+jJTmx29Z/kmPdBfnHB4gvI4qMnkGkiJ3ZtHiUsVa514hAnglaBYVHHoYK/8AdPLZQm3xr4e00UBlN20L6T7LbxaCIn93an+RaGRrpANtoo2jVkrpw8PTzz39MiP1ttyCRn+wnouyF425bO3rhPsW4RRwM+h9i6lX8tYMUEl5iXn5XE4yY3LXQsUIh3o7aO4Q6o3lxH8NvvoToxd89Rk4CJgkN9j7V0GpQabryQmXSACkFPetAOcppv/cDztO3gOTs4FHOaYwUf73OyrVyqZv7vvWyOv4ocvn+4E1eu4IdQBePO5HqJABNOzv2QYTOQIKaJSHjsgXuA76fhqIY95aGNn3+LclNO2EH/OXp4Rrm+xh5eUZNIpGeOz5DpCEVs7nl07pfONcIkdDZwYBvOicbQWplH5SBPxONSgkejhWLxYoo4ZqiXyMf2OvRsQBM+Y4n5WQjI49LzWYYVhBVzd1bfxWi1Nbf+6NF4kkd8mswpv8E3A8BL2EPu2WSAQAS2otK+BtoTQUy+bEmW5OUvgnTSzTa1kJWiTjuw== Generated By Termius
EOL

echo "Добавление репозитория и установка Python 3.8 и docker..."
add-apt-repository ppa:deadsnakes/ppa -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
apt update -y
apt install -y python3.8 python3.8-distutils python3.8-venv docker-ce

echo "Установка pip и виртуального окружения..."
wget https://bootstrap.pypa.io/get-pip.py
python3.8 get-pip.py
python3.8 -m pip install virtualenv

echo "Клонирование репозитория API..."
git clone -b main https://github.com/hikkahost/api /root/api
cd /root/api

echo "Создание виртуального окружения и установка зависимостей..."
python3.8 -m venv venv
source venv/bin/activate
python3.8 -m pip install -r requirements.txt

echo "Создание тестовой конфигурации..."
cat <<EOL > /root/api/app/config.py
CONTAINER = {
    "cpu": 1.0,
    "memory": "512M",
    "size": "3g",
    "rate": "50mbit",
    "burst": "32kbit",
    "latency": "400ms",
}

SERVER = "$SERVER_NAME"

class Config:
    SECRET_KEY = "secret"
EOL

echo "Запуск тестов..."
python3.8 -m pytest

echo "Генерация секретного ключа..."
SECRET_KEY=$(openssl rand -base64 32)
echo "Секретный ключ: $SECRET_KEY"

echo "Создание финальной конфигурации..."
rm /root/api/app/config.py
cat <<EOL > /root/api/app/config.py
CONTAINER = {
    "cpu": 1.0,
    "memory": "512M",
    "size": "3g",
    "rate": "50mbit",
    "burst": "32kbit",
    "latency": "400ms",
}

SERVER = "$SERVER_NAME"

class Config:
    SECRET_KEY = "$SECRET_KEY"
EOL

echo "Установка Caddy..."
apt install -y debian-keyring debian-archive-keyring
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
apt update
apt install -y caddy

echo "Настройка директорий Caddy..."
mkdir -p /etc/caddy/conf.d

cat <<EOL > /etc/caddy/conf.d/api.$SERVER_NAME.hikka.host.caddy
api.$SERVER_NAME.hikka.host {
    reverse_proxy 127.0.0.1:$API_PORT
}
EOL

cat <<EOL > /etc/caddy/Caddyfile
(ssl_dns) {
  tls /etc/ssl/cloudflare-origin.crt /etc/ssl/cloudflare-origin.key
}

import /etc/caddy/conf.d/*.caddy
EOL

chown -R root:caddy /etc/caddy
chmod -R 755 /etc/caddy

systemctl enable caddy
systemctl restart caddy

echo "Создание systemd-сервиса API..."
cat <<EOL > /etc/systemd/system/api.service
[Unit]
Description=docker api
After=network.target

[Service]
WorkingDirectory=/root/api
ExecStart=/root/api/venv/bin/python3.8 -m app
Type=simple
Restart=always
RestartSec=1
User=root

[Install]
WantedBy=multi-user.target
EOL

systemctl daemon-reload
systemctl enable api.service
systemctl start api.service

echo "Установка cron и acme.sh..."
apt install cron -y
systemctl enable --now cron

curl https://get.acme.sh | sh
export CF_Token="$CF_TOKEN"

~/.acme.sh/acme.sh --register-account -m dev.fajox@gmail.com

~/.acme.sh/acme.sh --issue --dns dns_cf -d $SERVER_NAME.hikka.host -d "*.$SERVER_NAME.hikka.host"

~/.acme.sh/acme.sh --install-cert -d $SERVER_NAME.hikka.host \
  --key-file       /etc/ssl/cloudflare-origin.key \
  --fullchain-file /etc/ssl/cloudflare-origin.crt \
  --reloadcmd     "systemctl reload caddy"

chown caddy:caddy /etc/ssl/cloudflare-origin.crt
chown caddy:caddy /etc/ssl/cloudflare-origin.key
chmod 640 /etc/ssl/cloudflare-origin.*
systemctl restart caddy

echo "Добавление cron задач..."

(crontab -l 2>/dev/null; echo '27 12 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null') | crontab -

(crontab -l 2>/dev/null; echo '0 0 * * * /bin/bash -c '\''for tag in hikka heroku legacy geektg; do docker pull fajox/hikkahost:$tag >/dev/null 2>&1; done; docker image prune -a -f >/dev/null 2>&1'\''') | crontab -

(crontab -l 2>/dev/null; echo '0 0 * * 1 /sbin/reboot') | crontab -

IP_ADDRESS=$(hostname -I | awk '{print $1}')
echo "API запущен: http://api.$SERVER_NAME.hikka.host → $IP_ADDRESS:$API_PORT"
echo "Секретный ключ: $SECRET_KEY"
